#! /bin/bash

cd "$(dirname "$0")"

str=""
NEWLINE=$'\n'
if [ $1 == '' ]
then
  # Read from std in
  while IFS='' read -r line
  do
    str="${str}${line}${NEWLINE}"
  done
  ./node_modules/.bin/babel-node ./markua.js "${str}"
else
  ./node_modules/.bin/babel-node ./markua.js $1
fi
